steps:
  #1단계 => docker-compose -f docker-compose.prod.yaml build
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - build
  #2단계 => docker-compose -f docker-compose.prod.yaml push
  - name: docker/compose:1.29.0
    args:
      - -f
      - class/deploy-with-docker/backend/docker-compose.prod.yaml
      - push

  #3단계 kubectl set image deployments/my-database-image1 my-backend02-sha256-1=asia.gcr.io/test1-347705/my-backend02:2.2.5
  - name: gcr.io/cloud-builders/kubectl
    args:
      - set
      - image
      - deployment/my-database-image1
      - my-backend02-sha256-1=asia.gcr.io/test1-347705/my-backend02:2.2.7
    env:
      - CLOUDSDK_COMPUTE_ZONE=asia-northeast3
      - CLOUDSDK_CONTAINER_CLUSTER=autopilot-cluster-02-1
